### ISSUE TITLE
Return value is still a promise

### ISSUE THREAD

**Issue by thany** [Magnetme/ng-async#9]
I though the whole premise of this service would be to write code that looks sync, while it's async under the bonnet.

So considering the example on your site:
```javascript
const initialize = $async(function*() {
	$scope.user = yield users.getActiveUser();
	$scope.messages = yield conversations.getMessagesFor($scope.user);
});
```
I would expect `initialize` to contain an **array with the two values** these promises were resolved with. Instead, `initialize` contains a single promise. So it *still* requires the use of those pesky `.then()` constructions, exactly the things we were trying to get rid of using the `await` keyword...

**Comment by TiddoLangerak** [comment]
That is intended: `ng-async` mimics how native async functions in Javscript work, and async functions also always return a promise (they have to: JS is non-blocking, so you can't perform an async operation and expect the result to appear synchronously). 

However, in the bigger picture you still rarely need to use `.then`: if we take the above example, then chances are we'll use it in another `$async` function, in which case we can `yield` on it:

```javascript
$async(function*() {
    yield initialize();
    //user & messages are now initialized
});
```

Using this approach it's possible to avoid `.then` completely. You can always put calls to async functions in other async functions and use `yield` to wait for the result.

I'm closing this issue because this isn't a bug, but feel free to continue the discussion if you like 🙂
